# Generated by Django 5.2.9 on 2026-01-23 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('TASK', 'Task'), ('FEATURE', 'Feature')], default='TASK', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project'], name='tickets_tic_project_ef7556_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['issue_type'], name='tickets_tic_issue_t_778aed_idx'),
        ),
    ]
