# Generated by Django 5.2.9 on 2026-01-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_issue_type_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
